import { useState } from 'react';
import { Activity, ArrowRight, Building2, CalendarDays, ChevronDown, ChevronUp, CircleDollarSign, ClipboardCheck, FileText, Home, LogOut, MapPin, Menu, Plus, Settings, ShieldCheck, Users, X } from 'lucide-react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const locations=[
  {name:'Express Dental',city:'Baltimore, MD',status:'Active',patients:8,today:'3 appointments',plan:'Clinical platform'},
  {name:'North Harbor Dental',city:'Annapolis, MD',status:'Setup required',patients:0,today:'—',plan:'Pending setup'},
];
const activity=[
  ['Location settings updated','Express Dental','2h ago'],
  ['Document policy updated','Express Dental','5h ago'],
  ['User added','North Harbor Dental','1d ago'],
  ['Appointment settings updated','Express Dental','1d ago'],
  ['Billing settings updated','North Harbor Dental','2d ago'],
];
const nav=[['Home',Home],['Organizations',Building2],['Locations',MapPin],['Patients',Users],['Appointments',CalendarDays],['Billing',CircleDollarSign],['Documents',FileText],['Audit',ShieldCheck]];

function Brand(){return <div className="brand"><span className="mark" aria-hidden="true"><i/><b/></span><span>Kantage<br/>Healthcare</span></div>}
function Sidebar({active,setActive,open,setOpen}){return <aside className={open?'sidebar open':'sidebar'}><div className="side-top"><Brand/><button className="close-nav" aria-label="Close navigation" onClick={()=>setOpen(false)}><X size={20}/></button><nav>{nav.map(([label,Icon])=><button key={label} className={active===label?'nav-item active':'nav-item'} onClick={()=>{setActive(label);setOpen(false)}}><Icon size={20}/><span>{label}</span></button>)}</nav></div><div className="side-bottom"><button className="nav-item"><Settings size={20}/><span>Settings</span></button><button className="nav-item"><LogOut size={20}/><span>Sign out</span></button></div></aside>}
function Status({value}){return <span className={value==='Active'?'status active-status':'status setup-status'}><i/>{value}</span>}
function AddLocation({close,onAdd}){const [name,setName]=useState('');const [city,setCity]=useState('');return <div className="overlay" role="presentation"><form className="dialog" onSubmit={event=>{event.preventDefault();onAdd({name,city,status:'Setup required',patients:0,today:'—',plan:'Pending setup'});close()}}><div className="dialog-head"><div><h2>Add a location</h2><p>Create a private workspace for a practice location.</p></div><button type="button" className="icon-button" onClick={close}><X size={20}/></button></div><label>Practice name<input value={name} required placeholder="Practice name" onChange={event=>setName(event.target.value)}/></label><label>City and state<input value={city} required placeholder="Baltimore, MD" onChange={event=>setCity(event.target.value)}/></label><div className="dialog-actions"><button type="button" className="secondary" onClick={close}>Cancel</button><button type="submit" className="primary">Create location</button></div></form></div>}
function HomeScreen({setActive,rows,setRows}){const [showDialog,setShowDialog]=useState(false);const [selected,setSelected]=useState(null);return <><main className="content"><section className="main-panel"><div className="title-row"><div><h1>Your healthcare operations</h1><p>Manage each organization and location from one secure place.</p></div><button className="primary add-button" onClick={()=>setShowDialog(true)}><Plus size={20}/>Add location</button></div><div className="table-wrap"><table><thead><tr><th>Location <ChevronUp className="sort" size={15} aria-label="Sorted ascending"/></th><th>Status</th><th>Patients</th><th>Today</th><th>Action</th></tr></thead><tbody>{rows.map((row,index)=><tr key={`${row.name}-${index}`}><td><strong>{row.name}</strong><small>{row.city}</small></td><td><Status value={row.status}/></td><td>{row.patients}</td><td>{row.today}</td><td><button className="open-button" onClick={()=>setSelected(row)}>Open <ArrowRight size={17}/></button></td></tr>)}</tbody></table></div></section><section className="service-banner"><Activity size={39}/><div><strong>All systems operational</strong><span>Kantage Healthcare is running smoothly.</span></div><small>Service status<br/><b>Healthy</b></small></section></main><aside className="right-rail"><section className="rail-section"><h2>Attention</h2><button className="attention" onClick={()=>setActive('Locations')}><span className="warning">!</span><span><strong>North Harbor Dental</strong><small>Complete location setup</small></span><ArrowRight size={18}/></button><button className="attention" onClick={()=>setActive('Billing')}><span className="warning">!</span><span><strong>Add billing details</strong><small>Enable billing to process claims</small></span><ArrowRight size={18}/></button></section><section className="rail-section audit"><div className="rail-heading"><h2>Recent audit activity</h2><button onClick={()=>setActive('Audit')}>View all</button></div>{activity.map(([event,place,time])=><div className="activity" key={event}><span><strong>{event}</strong><small>{place}</small></span><time>{time}</time></div>)}</section></aside>{showDialog&&<AddLocation close={()=>setShowDialog(false)} onAdd={entry=>setRows([...rows,entry])}/>} {selected&&<div className="overlay"><section className="dialog location-dialog"><div className="dialog-head"><div><h2>{selected.name}</h2><p>{selected.city} · {selected.plan}</p></div><button className="icon-button" onClick={()=>setSelected(null)}><X size={20}/></button></div><div className="workspace-actions"><button className="workspace-action" onClick={()=>setActive('Patients')}><Users/><span>Patients</span><ArrowRight/></button><button className="workspace-action" onClick={()=>setActive('Appointments')}><CalendarDays/><span>Appointments</span><ArrowRight/></button><button className="workspace-action" onClick={()=>setActive('Billing')}><CircleDollarSign/><span>Billing</span><ArrowRight/></button></div></section></div>}</>}
function Workspace({name}){return <main className="content workspace"><h1>{name}</h1><p>This area will show only the information your staff role is permitted to access.</p><div className="empty"><ClipboardCheck size={42}/><h2>{name} is ready for your workflow</h2><p>Select a location from Home to begin.</p></div></main>}
function App(){const [active,setActive]=useState('Home');const [menuOpen,setMenuOpen]=useState(false);const [rows,setRows]=useState(locations);return <div className="app-shell"><Sidebar active={active} setActive={setActive} open={menuOpen} setOpen={setMenuOpen}/><div className="page"><header><button className="menu-button" aria-label="Open navigation" onClick={()=>setMenuOpen(true)}><Menu size={22}/></button><span className="greeting">Good morning, Ibrahim</span><button className="profile"><span>IB</span><b>Ibrahim Barry<small>Administrator</small></b><ChevronDown size={18}/></button></header><div className="body">{active==='Home'?<HomeScreen setActive={setActive} rows={rows} setRows={setRows}/>:<Workspace name={active}/>}</div></div></div>}

createRoot(document.getElementById('root')).render(<App/>);
